#!/bin/sh

#
# listtables
# Development database table list utility.
#
# Copyright (C) 2013-2014 Unity <http://unitycore.org/>
#

if [ $# -lt 4 ]; then
  echo "usage: $0 DBUSER DBPASS DATABASE_NAME DIRECTORY_NAME"
  exit 1
fi

# Get db credentials
DBUSER=${1}
DBPASS=${2}
DBNAME=${3}

# Get dir name
DIRNAME=${4}

mysqlshow -u $DBUSER -p$DBPASS $DBNAME | grep -v "+" | grep -v "Tables" | grep -v ":" | tr -d "|" | cut -c 2- > $DIRNAME/$DIRNAME.list

# EOF
